require 'aruba/rspec'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.

RSpec.configure do |config|
  # Enable flags like --only-failures and --next-failure
  config.example_status_persistence_file_path = ".rspec_status"

  # Disable RSpec exposing methods globally on `Module` and `main`
  config.disable_monkey_patching!

  # Run specs in random order to surface order dependencies
  config.order = :random

  # Configure Aruba
  config.include Aruba::Api, type: :aruba

  # Setup for Aruba
  config.before(:each, type: :aruba) do
    setup_aruba
  end
end

# Configure Aruba
Aruba.configure do |config|
  # Set working directory for Aruba
  config.working_directory = 'tmp/aruba'
  
  # Set command timeout (in seconds)
  config.exit_timeout = 10
  
  # Set IO wait timeout (in seconds)
  config.io_wait_timeout = 2
end
